version: '3.8'

networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  prometheus_data:
  grafana-data:
  
services:
  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--storage.tsdb.retention.time=15d'
      # - '— config.file=/etc/prometheus/prometheus.yml'
      # - '— storage.tsdb.path=/prometheus'
      # - '— web.console.libraries=/etc/prometheus/console_libraries'
      # - '— web.console.templates=/etc/prometheus/consoles'
      # - '— web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.3.2-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      # - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

